config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/_admin', as: 'rails_admin'
  devise_for :admins
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    match '/users/auth/:provider/setup' => 'users/omniauth_callbacks#setup', via: :get
  end
  namespace :admins do
    %i(activities activities_contexts answers contexts events interactions memberships notifications levels projects users versions).each do |route|
      resources route.to_sym
    end
    root to: 'levels#index'
  end
  namespace :users do
    resource :account
    get 'performance' => 'accounts#performance'
    namespace :publisher do
      get :token
    end
    resources :contexts
    resources :events
    resources :notifications
    resources :interactions
    resources :activities do
      resources :answers
      resource :interaction
    end
  end
end

app/models/activities_context.rb
class ActivitiesContext < ApplicationRecord
  belongs_to :activity
  belongs_to :context
  default_scope -> { order(:position) }
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :organization
  has_many :activities_context
  has_many :answers
  has_many :contexts, through: :activities_context
  has_many :interactions
  enum kind: %w(publisher pdf video)
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_and_belongs_to_many :organizations
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :activity
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/context.rb
class Context < ApplicationRecord
  belongs_to :organization
  belongs_to :level
  has_many :activities_context
  has_many :activities, through: :activities_context
  has_many :interactions, through: :activities
  has_many :memberships
  has_many :users, through: :memberships
  has_many :events
  has_many :notifications
  has_ancestry cache_depth: true

  def ancestry=(value)
    super value.blank? ? nil : value
  end

  def tree
    family.arrange_serializable[0]
  end

  def parent_enum
    self.class.where.not(id: id).pluck(:name, :id)
  end

  def serializable_hash(params = {})
    super params.merge(include: [:activities, :level])
  end

  def family
    subtree.ordered_by_ancestry.or(path)
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :context
end

app/models/interaction.rb
class Interaction < ApplicationRecord
  belongs_to :user
  belongs_to :activity
  has_many :contexts, through: :activity
  after_create :validate_completion

  private

  def validate_completion
    contexts.each do |context|
      create_notification(context) if interacted_with_all_activities?(context)
    end
  end

  def create_notification(context)
    Notification.create!(user: user, body: "Parabéns! Você concluiu a(o) #{context.level.name} #{context.name}.")
  end

  def interacted_with_all_activities?(context)
    context.activities.count == context.interactions.where(user_id: user).count
  end
end

app/models/level.rb
class Level < ApplicationRecord
  belongs_to :project
  belongs_to :version
  belongs_to :parent, class_name: 'Level'
  has_many :contexts
  validates :parent_id, uniqueness: true
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :context
  enum role: %w(student teacher)
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :context
  belongs_to :user
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_and_belongs_to_many :admins
  has_many :activities
  has_many :activities_contexts, through: :contexts
  has_many :answers, through: :activities
  has_many :contexts
  has_many :events, through: :contexts
  has_many :interactions, through: :activities
  has_many :memberships, through: :contexts
  has_many :notifications, through: :users
  has_many :projects
  has_many :levels, through: :projects
  has_many :users
  has_many :versions
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :organization
  has_many :levels
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :token_authenticatable, :omniauthable, omniauth_providers: [:office365]
  mount_uploader :avatar, AvatarUploader
  belongs_to :organization
  has_many :answers
  has_many :interactions
  has_many :memberships
  has_many :notifications
  has_many :contexts, through: :memberships

  def notifications
    Notification.where(user_id: self).or(Notification.where(context_id: contexts_family_ids))
  end

  def events
    Event.where(context_id: contexts_family_ids)
  end

  def performance
    answers.joins(activity: :contexts).order('contexts.ancestry_depth, contexts.position, activities_contexts.position, answers.object_id').select('answers.activity_id, contexts.ancestry_depth as context_depth, contexts.position as context_position, activities_contexts.position as activities_context_position, answers.object_id, (case when given_option = expected_option then 1 else 0 end) as score, (select avg(case when given_option = expected_option then 1 else 0 end) from answers a where a.activity_id = answers.activity_id and a.object_id = answers.object_id and a.user_id != answers.user_id) as average')
  end

  private

  def contexts_family_ids
    contexts.map { |context| context.family.pluck(:id) }.flatten
  end

  def password_required?
    false
  end
end

app/models/version.rb
class Version < ApplicationRecord
  belongs_to :organization
end

app/controllers/admins/users_controller.rb
module Admins
  class UsersController < ResourcefulController
    def permitted_attributes
      [:name, :email, :login, :avatar, :phone, :rdp_library_token]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  respond_to :html, :json

  def current_organization
    @organization ||= Organization.find_by!(uid: request.host.split('.')[0])
  end
end

app/controllers/users/base_controller.rb
module Users
  class BaseController < ApplicationController
    before_action :authenticate_user!
  end
end

app/controllers/users/events_controller.rb
module Users
  class EventsController < BaseController
    def index
      respond_with current_user.events
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/admin.haml
!!!
%html
  %head
    %title RDP Manager
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" }
    %link{ href: "http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300ita‌​lic,400italic,500,500italic,700,700italic,900italic,900", rel: "stylesheet", type: "text/css" }
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top
      .container-fluid
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{ href: admins_root_path }
            = image_tag("/logo.png")
        #navbar.navbar-collapse.collapse
          %ul.nav.navbar-nav.navbar-right
            %li= link_to 'Sair', destroy_admin_session_path, data: { method: :delete }
    .container-fluid
      - flash.each do |name, msg|
        = content_tag(:div, msg, class: "alert alert-#{name}")
      .row
        .col-sm-3.col-md-2.sidebar
          %ul.nav.nav-sidebar
            %li.first= 'Admin - Novo LMS Ânima'
            - %w(activity activities_context answer context event interaction membership notification level project user version).sort_by { |class_name| t class_name, scope: %i(activerecord models) }.each do |class_name|
              %li{ class: (controller_name == class_name.pluralize ? "active" : "") }
                = link_to url_for(controller: "admins/#{class_name.pluralize}", action: :index) do
                  = t(class_name, scope: %i(activerecord models)).pluralize(I18n.locale)
        .col-sm-9.col-sm-offset-3.col-md-10.col-md-offset-2.main= yield

app/views/layouts/application.haml
!!!
%html
  %head
    %title RDP Manager
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" }
    %link{ href: "http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300ita‌​lic,400italic,500,500italic,700,700italic,900italic,900", rel: "stylesheet", type: "text/css" }
  %body
    .container-fluid
      - flash.each do |name, msg|
        = content_tag(:div, msg, class: "alert alert-#{name}")
      .col-md-12= yield